# Generated by Django 4.2.6 on 2023-11-11 20:33

import datetime
from django.db import migrations, models
import django.utils.timezone
import home_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=225)),
                ('updated', models.DateField(default=datetime.date.today)),
                ('language', models.CharField(default=home_app.models.default_language, max_length=30)),
                ('noOfStudent', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/courses')),
            ],
        ),
    ]
